version: '3.5'

services:
  db:
    hostname: db.metrics-server.octobot.online
    image: mongo
    ports:
      - 27017:27017
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./data/db:/data/db

  web:
    image: drakkarsoftware/metrics-server.octobot.online
    environment:
      - MONGODB_URI=mongodb://localhost:27017/metrics
    hostname: metrics-server.octobot.online
    links:
      - db
    ports:
      - 3000:3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m
