name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag drakkarsoftware/metrics-server.octobot.online --tag drakkarsoftware/octobot-metrics-server
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: drakkarsoftware/metrics-server.octobot.online
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: drakkarsoftware/octobot-metrics-server
        username: ${{ secrets.DOCKER_T_USERNAME }}
        password: ${{ secrets.DOCKER_T_PASSWORD }}
        registry: ${{ secrets.DOCKER_T_REPO }}
