name: Metrics-Server - Docker

on: [ push ]

jobs:
  lint:
    name: ubuntu-latest - Docker - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          hadolint_ignore: DL3013 DL3008

  build:
    name: ubuntu-latest - Docker - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          OWNER="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' | tr -d '-')"
          IMG=metrics.octobot.online
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "IMAGE=${OWNER}/${IMG}" >> $GITHUB_ENV
          echo "LATEST=latest" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags') && github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ env.LATEST }}

      - name: Build and push on tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.LATEST }}
            ${{ env.IMAGE }}:${{ env.VERSION }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    if: ${{ failure() }}

    steps:
      - name: Notify discord
        uses: sarisia/actions-status-discord@v1
        with:
          status: Failure
          webhook: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
